from .generic_loss import *
from .cluster_loss import *
from .l1_loss import *
from .l2_loss import *
from .l2output_loss import *
from .latent_wasserstein_loss import *
from .latent_wasserstein_valid import *
from .latent_wasserstein_invalid import *
from .latent_binary_loss import *
from .single_latent_wasserstein_loss import *
from .wasserstein_loss import *
from .loss_handler import *